"""Transaction logic changes

Revision ID: db73a20724a9
Revises: 5a0e3a86155d
Create Date: 2025-09-11 13:43:27.420920

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'db73a20724a9'
down_revision: Union[str, Sequence[str], None] = '5a0e3a86155d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('sender_account_id', sa.Integer(), nullable=False))
    op.add_column('transactions', sa.Column('recipient_account_id', sa.Integer(), nullable=False))
    op.drop_constraint(op.f('transactions_recipient_id_fkey'), 'transactions', type_='foreignkey')
    op.drop_constraint(op.f('transactions_sender_id_fkey'), 'transactions', type_='foreignkey')
    op.create_foreign_key(None, 'transactions', 'accounts', ['recipient_account_id'], ['id'])
    op.create_foreign_key(None, 'transactions', 'accounts', ['sender_account_id'], ['id'])
    op.drop_column('transactions', 'recipient_id')
    op.drop_column('transactions', 'sender_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('sender_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('transactions', sa.Column('recipient_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.create_foreign_key(op.f('transactions_sender_id_fkey'), 'transactions', 'users', ['sender_id'], ['id'])
    op.create_foreign_key(op.f('transactions_recipient_id_fkey'), 'transactions', 'users', ['recipient_id'], ['id'])
    op.drop_column('transactions', 'recipient_account_id')
    op.drop_column('transactions', 'sender_account_id')
    # ### end Alembic commands ###
